name: Package
description: Packages binaries for deployment

inputs:
  platform:
    description: 'Binary platform'
    required: true
  framework: 
    description: '.net framework'
    required: true
  artifact:
    description: 'Binary artifact'
    required: true
  branch:
    description: 'Git branch used for this build'
    required: true
  major_version:
    description: 'Sonarr major version'
    required: true
  app_version:
    description: 'Sonarr app version'
    required: true
  release_version:
    description: 'Sonarr fork release version'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Download Artifact
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
      with:
        name: ${{ inputs.artifact }}
        path: _output

    - name: Download UI Artifact
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
      with:
        name: build_ui
        path: _output/UI

    - name: Configure Environment Variables
      shell: bash
      run: |
        echo "FRAMEWORK=${{ inputs.framework }}" >> "$GITHUB_ENV"
        echo "BRANCH=${{ inputs.branch }}" >> "$GITHUB_ENV"
        echo "SONARR_MAJOR_VERSION=${{ inputs.major_version }}" >> "$GITHUB_ENV"
        echo "APP_VERSION=${{ inputs.app_version }}" >> "$GITHUB_ENV"
        echo "RELEASE_VERSION=${{ inputs.release_version }}" >> "$GITHUB_ENV"

    - name: Create Packages
      shell: bash
      run: $GITHUB_ACTION_PATH/package.sh

    - name: Create Windows Installer (x64)
      if: ${{ inputs.platform == 'windows' }}
      working-directory: distribution/windows/setup
      shell: cmd
      run: |
        SET RUNTIME=win-x64

        build.bat

    - name: Create Windows Installer (x86)
      if: ${{ inputs.platform == 'windows' }}
      working-directory: distribution/windows/setup
      shell: cmd
      run: |
        SET RUNTIME=win-x86

        build.bat

    - name: Upload Artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: release_${{ inputs.platform }}
        compression-level: 0
        if-no-files-found: error
        retention-days: 7
        path: |
          _artifacts/*.exe
          _artifacts/*.tar.gz
          _artifacts/*.zip
